[pytest]
pythonpath = .
testpaths = tests/unit
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning:websockets.legacy.*
    ignore:enable_cleanup_closed ignored:DeprecationWarning:aiohttp.connector